export const SHOW_FILMS = "SHOW_FILMS";
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const HANDLER_INPUT = 'HANDLER_INPUT'
export const GET_GENRES = 'GET_GENRES'
export const SET_SELECTED_FILTER = 'SET_SELECTED_FILTER'
export const SET_FAVOURITE_FILMS = 'SET_FAVOURITE_FILMS'
export const DELETE_FAVOURITE_FILMS = 'DELETE_FAVOURITE_FILMS'
export const SET_SELECTED_FILM_ID = 'SET_SELECTED_FILM_ID'
export const DELETE_SELECTED_FILM_ID = 'DELETE_SELECTED_FILM_ID'
export const GET_VIDEO = 'GET_VIDEO'
export const CHANGE_THEME = 'CHANGE_THEME'
export const API_KEY = "303097b4-2b0a-46a5-8aae-4a1137273ff1";

